# Generated by Django 3.0 on 2021-06-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FullName', models.CharField(blank=True, max_length=500, null=True)),
                ('ProfileImage', models.CharField(blank=True, max_length=1000, null=True)),
                ('EmailId', models.EmailField(max_length=254)),
                ('ShortDescription', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
