# Generated by Django 3.0 on 2021-06-16 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationalDetails',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Degree', models.CharField(blank=True, max_length=500, null=True)),
                ('YearOfPassing', models.IntegerField(choices=[(2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025)], default=2021, verbose_name='year')),
                ('CertificateImage', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('UserProfileId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserProfile.user_profile')),
            ],
        ),
    ]
