# Generated by Django 3.0 on 2021-06-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0004_auto_20210617_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='ProfileImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
