# Generated by Django 3.0 on 2021-06-18 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfile', '0005_auto_20210617_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationaldetails',
            name='UserProfileId',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='EducationDetails',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserProfile.EducationalDetails'),
        ),
    ]
